### ISSUE TITLE
Objects Deleted are still showing in the screen

### ISSUE THREAD

**Issue by DioDuarte** [Borf/BrowEdit3#1]
If i add an object and then delete it, it will still appear to be in the map but you cannot select it anymore.

![image](https://user-images.githubusercontent.com/86444764/159140738-347f0025-8262-4401-ac6d-6683ba232813.png)

**Comment by DioDuarte** [comment]
> If i add an object and then delete it, it will still appear to be in the map but you cannot select it anymore.
> 
> ![image](https://user-images.githubusercontent.com/86444764/159140738-347f0025-8262-4401-ac6d-6683ba232813.png)

It disappears when i put another object in the map.

**Comment by Borf** [comment]
This should be fixed by now. Was due to doube renderers being added
